In [10]:
#import 
import numpy as np
import pandas as pd
import random

In [11]:
ost40 = pd.read_csv("../../../input/ost40.csv", sep=',', index_col=0)
ost40

    Y  LI  SEX  AOP
0   1   1    1    1
1   1   0    1    0
2   1   0    0    0
3   0   1    1    1
4   0   1    1    1
5   1   1    0    0
6   0   1    1    0
7   0   1    1    1
8   0   1    1    1
9   1   1    0    1
10  1   0    0    0
11  1   1    1    1
12  0   1    1    1
13  1   0    0    1
14  1   0    0    0
15  0   1    1    0
16  1   1    0    1
17  1   0    1    0
18  0   1    1    0
19  0   1    1    1
20  1   1    1    0
21  1   1    1    0
22  1   1    0    0
23  1   1    1    1
24  1   1    1    1
25  1   1    1    1
26  1   1    1    1
27  1   0    1    0
28  1   1    1    0
29  0   1    1    0
30  0   1    1    1
31  1   1    0    0
32  1   1    0    1
33  0   1    0    1
34  0   1    1    1
35  0   1    1    1
36  1   1    0    0
37  1   1    1    0
38  1   1    1    0
39  0   1    1    1

In [12]:
def make_t_list(df):
    t_list = []
    t_list.append(sum(df['Y']))
    t_list.append(0)
    t_list.append(np.dot(df['Y'], df['SEX']))
    t_list.append(np.dot(df['Y'], df['AOP']))
    
    return t_list

In [13]:
t_list = make_t_list(ost40)

### make data

In [14]:
def dotXY(x, y):
    if x==0:
        return 0
    else:
        return 1

In [15]:
# make .mat data
def make_mat(num_samples, feature1, feature2, feature3):
    mat_data = []
    
    #yの各要素が0, 1であることを示している
    for m in range(num_samples):
        all0 = [0]*num_samples
        all0[m] = 1
        mat_data.append(all0)
        
    mat_data.append([1]*num_samples) 
    mat_data.append([1]*num_samples)
    
    mat_data.append(feature1.values.tolist())
    mat_data.append(feature1.values.tolist())

    mat_data.append(feature2.values.tolist())
    mat_data.append(feature2.values.tolist())

    mat_data.append(feature3.values.tolist())
    mat_data.append(feature3.values.tolist())
    
    return mat_data

In [16]:
def make_data_for_4ti2(df, t_list, num_samples, feature1, feature2, feature3):
    mat = []
    mat_data = make_mat(num_samples, feature1, feature2, feature3)
    mat_shape =  [num_samples+2*len(t_list), num_samples]
    mat += [mat_data, mat_shape]
    
    rel = []
    rel_data = [["<"]*num_samples+[">", "<"]*len(t_list)]
    rel_shape = [1, num_samples+2*len(t_list)]
    rel += [rel_data, rel_shape]
    
    rhs = []
    rhs_data = [[1]*num_samples+[t_list[0]]*2+[t_list[1]]*2+[t_list[2]]*2+[t_list[3]]*2]
    rhs_shape = [1, num_samples+2*len(t_list)]
    rhs += [rhs_data, rhs_shape]
    
    sign = []
    sign_data = [[1]*num_samples]
    sign_shape = [1, num_samples]
    sign += [sign_data, sign_shape]
    
    return mat, rel, rhs, sign

In [17]:
mat, rel, rhs, sign = make_data_for_4ti2(ost40, t_list, ost40.shape[0], ost40['LI'], ost40['SEX'], ost40['AOP'])

In [9]:
mat_data = make_mat(ost16.shape[0], ost16['LI'], ost16['SEX'], ost16['AOP'])
print(mat_data)

mat_shape =  [ost16.shape[0]+2*len(t_list), ost16.shape[0]]
print(mat_shape)

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0], [1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0], [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0], [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0], [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1], [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1]]
[24, 16]

In [10]:
# make .rel data
rel_data = [["<"]*ost16.shape[0]+[">", "<"]*len(t_list)]
print(rel_data)

rel_shape = [1, ost16.shape[0]+2*len(t_list)]
print(rel_shape)

[['<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '<', '>', '<', '>', '<', '>', '<', '>', '<']]
[1, 24]

In [11]:
# make  .rhs data
rhs_data = [[1]*ost16.shape[0]+[t0]*2+[t1]*2+[t2]*2+[t3]*2]
print(rhs_data)

rhs_shape = [1, ost16.shape[0]+2*len(t_list)]
print(rhs_shape)

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 14, 14, 0, 0, 9, 9, 8, 8]]
[1, 24]

In [12]:
# make .sign data
sign_data = [[1]*ost16.shape[0]]
print(sign_data)

sign_shape = [1, ost16.shape[0]]
print(sign_shape)

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
[1, 16]

### make file

In [18]:
def save_system(path, shape, data):
  """
  使用例
  save_system("hoge.csv", (2, 4), [[1,1,1,1], [1,2,3,4]])
  save_system("hoge.rel", (1, 2), [["<", "<"]])
  """
  with open(path, "w") as f:
    f.write(" ".join([str(a) for a in shape])+"\n")
    for d in data:
        f.write(" ".join([str(a) for a in d])+"\n")

In [22]:
# make .mat file
save_system("0.mat", mat[1], mat[0])

In [23]:
# make .rel file
save_system("0.rel", rel[1], rel[0])

In [24]:
# make .rhs file
save_system("0.rhs", rhs[1], rhs[0])

In [25]:
# make .sign file
save_system("0.sign", sign[1], sign[0])