In [1]:
#import 
import numpy as np
import pandas as pd
import random

In [2]:
ost20 = pd.read_csv("../../../input/ost20.csv", sep=',', index_col=0)
ost20

    Y  LI  SEX  AOP
0   0   1    1    0
1   1   1    1    1
2   0   1    1    1
3   1   1    1    1
4   0   1    1    1
5   1   0    1    0
6   0   1    1    0
7   1   1    1    0
8   1   1    1    0
9   1   1    1    1
10  1   1    1    1
11  0   1    1    1
12  0   1    1    1
13  1   0    0    1
14  0   1    1    0
15  1   1    1    0
16  0   1    1    1
17  1   0    1    0
18  0   1    0    1
19  1   1    0    0

In [3]:
def make_t_list(df, num):
    t_list = []
    t_list.append(sum(df['Y']))
    t_list.append(num) #change
    t_list.append(np.dot(df['Y'], df['SEX']))
    t_list.append(np.dot(df['Y'], df['AOP']))
    
    return t_list

In [4]:
t_list = make_t_list(ost20, 16)

### make data

In [5]:
def dotXY(x, y):
    if x==0:
        return 0
    else:
        return 1

In [6]:
# make .mat data
def make_mat(num_samples, feature1, feature2, feature3):
    mat_data = []
    
    #yの各要素が0, 1であることを示している
    for m in range(num_samples):
        all0 = [0]*num_samples
        all0[m] = 1
        mat_data.append(all0)
        
    mat_data.append([1]*num_samples) 
    mat_data.append([1]*num_samples)
    
    mat_data.append(feature1.values.tolist())
    mat_data.append(feature1.values.tolist())

    mat_data.append(feature2.values.tolist())
    mat_data.append(feature2.values.tolist())

    mat_data.append(feature3.values.tolist())
    mat_data.append(feature3.values.tolist())
    
    return mat_data

In [7]:
def make_data_for_4ti2(df, t_list, num_samples, feature1, feature2, feature3):
    mat = []
    mat_data = make_mat(num_samples, feature1, feature2, feature3)
    mat_shape =  [num_samples+2*len(t_list), num_samples]
    mat += [mat_data, mat_shape]
    
    rel = []
    rel_data = [["<"]*num_samples+[">", "<"]*len(t_list)]
    rel_shape = [1, num_samples+2*len(t_list)]
    rel += [rel_data, rel_shape]
    
    rhs = []
    rhs_data = [[1]*num_samples+[t_list[0]]*2+[t_list[1]]*2+[t_list[2]]*2+[t_list[3]]*2]
    rhs_shape = [1, num_samples+2*len(t_list)]
    rhs += [rhs_data, rhs_shape]
    
    sign = []
    sign_data = [[1]*num_samples]
    sign_shape = [1, num_samples]
    sign += [sign_data, sign_shape]
    
    return mat, rel, rhs, sign

In [8]:
mat, rel, rhs, sign = make_data_for_4ti2(ost20, t_list, ost20.shape[0], ost20['LI'], ost20['SEX'], ost20['AOP'])

### make file

In [9]:
def save_system(path, shape, data):
  """
  使用例
  save_system("hoge.csv", (2, 4), [[1,1,1,1], [1,2,3,4]])
  save_system("hoge.rel", (1, 2), [["<", "<"]])
  """
  with open(path, "w") as f:
    f.write(" ".join([str(a) for a in shape])+"\n")
    for d in data:
        f.write(" ".join([str(a) for a in d])+"\n")

In [10]:
# make .mat file
save_system("16.mat", mat[1], mat[0])

In [11]:
# make .rel file
save_system("16.rel", rel[1], rel[0])

In [12]:
# make .rhs file
save_system("16.rhs", rhs[1], rhs[0])

In [13]:
# make .sign file
save_system("16.sign", sign[1], sign[0])